# reference: https://github.com/TencentBlueKing/bkpaas-python-sdk/tree/master/sdks/apigw-manager
spec_version: 2
release:
  version: "1.0.0"
  title: "初始版本"
  comment: "首次发布"
apigateway:
  description: "示例网关"
  description_en: "Example Gateway"
  is_public: true
  api_type: 10
  maintainers:
    - "handryhan"
  
stages:
  - name: "prod"
    description: "生产环境"
    description_en: "Production"
    vars:
      api_sub_path: /api
    backends:
      - name: "default"
        config:
          timeout: 30
          loadbalance: "roundrobin"
          hosts:
            - host: "http://api.example.com"
              weight: 100
    plugin_configs:
      - type: bk-header-rewrite
        yaml: |
          set:
              - key: X-Real-IP
                value: test
          remove:
              - key: X-Forwarded-For
          
grant_permissions:
  - bk_app_code: "app1"
    grant_dimension: "api"
  - bk_app_code: "app2"
    grant_dimension: "resource"
    resource_names:
      - "get_pet_by_id"
related_apps:
- "myapp"
resource_docs:
basedir: "/data/docs"